### ISSUE TITLE
Feature: Implement a Go client

### ISSUE THREAD

**Issue by joeblew99** [jpillora/velox#1]
This is great.

The patch functionality being used server to server and server to web client is reusable

I have 2 ideas :
1. As the data changes on the client, you want to be able to react to it. This is an interesting challenge. I am thinking a simple switch statement, almost like a reverse router. The programmer simply expressed changes in the strut they subscribe to.

2. East West agnostic. Using this just client server is awesome. But I can see it being useful between golang servers too.

**Comment by jpillora** [comment]
Yep, there's nothing preventing a server from hitting the same `/sync` endpoints that the browser would hit. This would just require a client implementation in Go. Will change this issue to be a request for a Go client. Not sure when I'll get time to do it though.

**Comment by joeblew99** [comment]
Ok thanks.

**Comment by joeblew99** [comment]
have not had a chance to look at this. Too crazy on current project.

**Comment by joeblew99** [comment]
i am closing for now.. i dont need this anymore.. Browser is perfectly fine
