### ISSUE TITLE
caching

### ISSUE THREAD

**Issue by joeblew99** [jpillora/velox#2]
The way that the data is held on the golang side is a pointer ?
So its a shared memory area, and so i was condering about using it as a cache, because it seems to make sense.
As such, i am thinking that some sort of management channel is needed, so that i can tell clients to drop their cache and reload. The reason i am thinking this is worthwhile is because the cache needs to be dropped and reloaded when upgrades happen etc. Otherwise there is a risk that the clients will think that all data has been dropped and react in inappropriate ways.

i could be wrong here of course, but as i was thinking through use cases of using this on a project, its what hit me.

What do you think ?

thanksn advance.

**Comment by jpillora** [comment]
Sorry forgot about this issue, whats your example use case for this? My main use case was to create a single global shared state to make responsive management web UIs. Another one is to create individual state objects to implement long lasting continous queries.

**Comment by joeblew99** [comment]
Raft for web :)

It's Ok. I worked around it. But that's.
